### ISSUE TITLE
Argument bug in common.py?

### ISSUE THREAD

**Issue by esidebo** [ac-tuwien/pymhlib#15]
Looks like `seed` argument will be taken as `args` here? (`add_general_arguments_and_parse_settings` takes three arguments where seed is the third) https://github.com/ac-tuwien/pymhlib/blob/0480dc966cb23488fec5615dd90b34dc904c3d65/pymhlib/demos/common.py#L67

**Comment by graidl** [comment]
Thanks for pointing this out. It is fixed now in the current master branch version.
